name: dwib_bank
version: 1.0.0
config-version: 2

profile: dwib_bank

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dwib_bank:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      dimensions:
        +materialized: table
      facts:
        +materialized: table
